[workspace]
members = ["packages/*"]
resolver = "2"

[workspace.dependencies]
vexide = { path = "../vexide/packages/vexide" }
evian = { path = "../evian" }
aubie2 = { path = "packages/aubie2" }
log = "0.4.22"
