[workspace]
members = ["packages/*"]
resolver = "2"

[workspace.dependencies]
vexide = "0.7.0"
evian = { git = "https://github.com/vexide/evian", rev = "40ff9109d4749d5b26d6bdbcce890ae52a5195e3" }
aubie2 = { path = "packages/aubie2" }
log = "0.4.22"