[package]
name = "orange"
version = "0.1.0"
edition = "2021"

[package.metadata.v5]
upload-strategy = "differential"
slot = 1
icon = "cool-x"

[dependencies]
aubie2 = { workspace = true }
vexide = { workspace = true }
evian = { workspace = true }
log = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(route, values("blue", "red", "blue_rush", "red_rush", "skills"))',
] }
