[package]
name = "blue"
version = "0.1.0"
edition = "2021"

[package.metadata.v5]
upload-strategy = "differential"
slot = 1
icon = "cool-x"

[dependencies]
aubie2 = { workspace = true }
vexide = { workspace = true }
evian = { workspace = true }
log = { workspace = true }
futures = { version = "0.3.31", default-features = false, features = ["async-await"] }